# 命令中数据库相关信息、容器相关信息此前如有修改，请确保前后信息一致

: "${MYSQL_ROOT_PASSWORD:?Set MYSQL_ROOT_PASSWORD}"
: "${MYSQL_REPLICATION_PASSWORD:?Set MYSQL_REPLICATION_PASSWORD}"

docker exec -i \
  -e MYSQL_PWD="$MYSQL_ROOT_PASSWORD" \
  insurance-mysql-slave \
  mysql -uroot -h127.0.0.1 <<SQL
CHANGE REPLICATION SOURCE TO SOURCE_HOST='192.168.56.107', SOURCE_PORT=3308,SOURCE_USER='insurancedev',SOURCE_PASSWORD='${MYSQL_REPLICATION_PASSWORD}', SOURCE_SSL = 1,SOURCE_LOG_FILE='mysql-bin.000002',SOURCE_LOG_POS=2;
START REPLICA;
SHOW REPLICA STATUS\G;
SQL
